version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  producer:
    build:
      context: ./producer
    container_name: producer
    ports:
      - "3002:3002"
    env_file:
      - ./producer/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    env_file:
      - ./consumer/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
